#!/usr/bin/env bash

env EXTRA_CMAKE_ARGS="-DPATH_TO_LLVM_ROOT=/eems/eems/dev/clang/linux/rh-6/stable" \
    PATH=/inf10xl_user1/third-party/go/bin:${PATH} \
    ./install.py --clang-completer --system-libclang --go-completer --quiet --java-completer "$@"
cd ./third_party/ycmd/third_party/tern_runtime
npm install --production
