#!/usr/bin/env bash

export EXTRA_CMAKE_ARGS="-DPATH_TO_LLVM_ROOT=$clang"

# Use system go on RHEL7 +
RHEL=$(lsb_release -s -r | sed 's/\..*//')
PREFIX=""
if [ $RHEL -lt "7" ]; then
    export PATH=/inf10xl_user1/third-party/go/bin:${PATH} 
else
    PREFIX="scl enable devtoolset-8 rh-python36 rh-nodejs10 rh-ruby25 --"
fi


$PREFIX python3 ./install.py --clang-completer \
                             --system-libclang \
                             --go-completer \
                             --java-completer "$@"
cd ./third_party/ycmd/third_party/tern_runtime
$PREFIX npm install --production
